# Generated by Django 4.2.3 on 2024-07-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ranking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teamname', models.CharField(db_column='TeamName', max_length=99)),
                ('points', models.IntegerField(db_column='Points')),
            ],
            options={
                'db_table': 'ranking',
            },
        ),
    ]
