# Generated by Django 4.2.3 on 2024-07-28 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ranktable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
