# Generated by Django 4.2.3 on 2024-07-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranktable', '0002_ranking_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='created',
        ),
    ]
