# Generated by Django 4.2.3 on 2024-07-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranktable', '0003_remove_ranking_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team1_name', models.CharField(max_length=99)),
                ('team1_score', models.IntegerField()),
                ('team2_name', models.CharField(max_length=99)),
                ('team2_score', models.IntegerField()),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
