name: Deploy Django to AWS (Simple SSH)

on:
  push:
    branches:
      - main  # deploy when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on AWS via SSH
        run: |
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            cd ${{ secrets.REMOTE_DIR }}
            sudo chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} ${{ secrets.REMOTE_DIR }}
            git config --global --add safe.directory ${{ secrets.REMOTE_DIR }}

            echo "Pulling latest code from GitHub..."
            git fetch origin main
            git reset --hard origin/main

            echo "Activating virtual environment..."
            source venv/bin/activate

            echo "Installing dependencies..."
            pip install -r requirements.txt

            echo "Running Django migrations..."
            python manage.py migrate --noinput

            echo "Collecting static files..."
            python manage.py collectstatic --noinput

            echo "Restarting services..."
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx

            echo "✅ Deployment successful!"
          EOF